import colors from "./colors";

export const common = {
  fontFamily:
    "'Sofia-pro', 'Open Sans', -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol",
};

const text = {
  headingXXL: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "40px",
    lineHeight: "56px",
    color: colors.neutral.ink.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  headingXL: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "28px",
    lineHeight: "40px",
    color: colors.neutral.ink.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  headingLarge: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "24px",
    lineHeight: "32px",
    color: colors.neutral.ink.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  headingMedium: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "20px",
    lineHeight: "28px",
    color: colors.neutral.ink.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  headingSmall: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "20px",
    color: colors.neutral.ink.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  headingTable: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "12px",
    lineHeight: "16px",
    color: colors.neutral.ink.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  subheadingLarge: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "20px",
    lineHeight: "28px",
    color: colors.neutral.ink.light,
    textDecoration: "none",
    letterSpacing: "0",
  },
  subheadingMedium: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "16px",
    lineHeight: "24px",
    color: colors.neutral.ink.light,
    textDecoration: "none",
    letterSpacing: "0",
  },
  subheadingSmall: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "12px",
    lineHeight: "16px",
    color: colors.neutral.ink.light,
    textDecoration: "none",
    letterSpacing: "0",
  },
  subheadingSmallBold: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "12px",
    lineHeight: "16px",
    color: colors.neutral.ink.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  body: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "14px",
    lineHeight: "20px",
    color: colors.neutral.ink.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  bodySmall: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "12px",
    lineHeight: "16px",
    color: colors.neutral.ink.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  bodyBold: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "20px",
    color: colors.neutral.ink.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  bodyBoldDark: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "20px",
    color: colors.neutral.ink.dark,
    textDecoration: "none",
    letterSpacing: "0",
  },
  bodySmallBold: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "12px",
    lineHeight: "16px",
    color: colors.neutral.ink.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  button: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "24px",
    color: colors.secondary.blue.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  buttonSmall: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "16px",
    color: colors.secondary.blue.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  linkLarge: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "20px",
    lineHeight: "28px",
    color: colors.secondary.blue.base,
    textDecoration: "underline",
    letterSpacing: "0",
  },
  linkMedium: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "16px",
    lineHeight: "24px",
    color: colors.secondary.blue.base,
    textDecoration: "underline",
    letterSpacing: "0",
  },
  link: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "14px",
    lineHeight: "20px",
    color: colors.secondary.blue.base,
    textDecoration: "underline",
    letterSpacing: "0",
  },
  linkSmall: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "12px",
    lineHeight: "16px",
    color: colors.secondary.blue.base,
    textDecoration: "underline",
    letterSpacing: "0",
  },
  inputLabel: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "24px",
    color: colors.neutral.ink.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  inputLabelSmall: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "12px",
    lineHeight: "16px",
    color: colors.neutral.ink.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  hintText: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "12px",
    lineHeight: "16px",
    color: colors.neutral.ink.light,
    textDecoration: "none",
    letterSpacing: "0",
  },
  placeholder: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "14px",
    lineHeight: "24px",
    color: colors.neutral.ink.lightest,
    textDecoration: "none",
    letterSpacing: "0",
  },
  placeholderSmall: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "12px",
    lineHeight: "16px",
    color: colors.neutral.ink.lightest,
    textDecoration: "none",
    letterSpacing: "0",
  },
  placeholderCode: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "14px",
    lineHeight: "24px",
    color: colors.neutral.ink.lightest,
    textDecoration: "none",
    letterSpacing: "0.5em",
  },
  placeholderCodeSmall: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "12px",
    lineHeight: "16px",
    color: colors.neutral.ink.lightest,
    textDecoration: "none",
    letterSpacing: "0.5em",
  },
  error: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "20px",
    color: colors.secondary.red.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  errorSmall: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "12px",
    lineHeight: "16px",
    color: colors.secondary.red.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
  successSmall: {
    fontFamily: common.fontFamily,
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "12px",
    lineHeight: "16px",
    color: colors.secondary.green.base,
    textDecoration: "none",
    letterSpacing: "0",
  },
};

export default text;
